### ISSUE TITLE
bsmap build cygwin64

### ISSUE THREAD

**Issue by muhammadjamil** [genome-vendor/bsmap#2]
I am trying to build bsmap on cygwin64 but its is giving me error 

param.h:75:13: Fehler: expected »)« before »->« token
     bit32_t stdout; bit8_t zero_qual, qual_threshold, default_qual; //51 byte
             ^
make: *** [makefile:16: align.o] Fehler 1

I feel like it is due to C++ error. But could you please guide me what is the issue?

**Comment by chrisamiller** [comment]
This is just our local copy of the bsmap code. We are not the developers. You should contact the Li lab for support: http://lilab.openwetware.org
