### ISSUE TITLE
Can't execute the make step

### ISSUE THREAD

**Issue by katha22** [genome-vendor/bsmap#4]
Following the install instruction of the readme doesn't work.

**System**:
`-bash-4.2$ uname -a
Linux login.cluster.de 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
**Error**:
`g++ -DMAXHITS=1000 -DTHREAD -funroll-loops -Lsamtools -Isamtools -Lgzstream -Igzstream -O3 -m64 -c param.cpp -o param.o
param.cpp: In constructor ‘Param::Param()’:
param.cpp:8:20: error: ‘_SC_NPROCESSORS_ONLN’ was not declared in this scope
param.cpp:8:40: error: ‘sysconf’ was not declared in this scope
make: *** [param.o] Error 1
`
**Solution:**
adding "#include<unistd.h>" in the beginning of param.cpp solved the issue

**Comment by katha22** [comment]
sorry didn't see the PR .. please merge

**Comment by tmooney** [comment]
Sorry, this is not an official `bsmap` repository. It is unmaintained and contains a years-outdated version of the codebase.  I would advise searching elsewhere for a more current version of the software.

Looks like this particular issue may have been addressed in version 2.90 according to: https://github.com/zyndagj/BSMAP/blob/3b7fa4d106c8a8750eaf2a611aab8c57940c2a0e/RELEASE.txt
