### ISSUE TITLE
About duplicate information

### ISSUE THREAD

**Issue by vanessayang0927** [genome-vendor/bsmap#5]
Hi,
I installed BSmap successfully and runned it without error. 
However, I did't found any duplicate information in the output methylation ratio file after finishing BSmap and methratio.py.
I wanted to ask a help for obtaining the duplicate information, like the number of duplicate reads.

**Comment by chrisamiller** [comment]
This is not the primary bsmap repository - it's just a convenience fork by some people using it. You're going to want to go here for help or support:
https://code.google.com/archive/p/bsmap/
